### ISSUE TITLE
Empty streams when running in Meltano

### ISSUE THREAD

**Issue by aroder** [frasermarlow/tap-bls#1]
### Issue
The code looks for the `series.json` file in the same directory as the `config.json` file. 

https://github.com/frasermarlow/tap-bls/blob/master/tap_bls/create_schemas.py#L21

Meltano generates a run directory and `config.json` file dynamically, so there is no opportunity to place a `series.json` file there. The result is a catalog with an empty streams array `"streams": []`

How can we configure this to function in Meltano? 

### Proposal
The `series.json` file location should be configurable in `config.json`, and default to the current behavior if no value is provided

**Comment by frasermarlow** [comment]
Thanks Adam.  Making the location of the series.json file a config parameter in config.json seems like a good approach.  Bear with me as I plug that in.
