### ISSUE TITLE
No such file or directory: 'config.json/state.json'

### ISSUE THREAD

**Issue by SteadyGiant** [frasermarlow/tap-bls#8]
Using Python 3.7 or 3.9 on Windows 10.

Install the tap and target:

```sh
python -m venv bls
bls/Scripts/pip install tap-bls  # bls/bin/pip on a Unix-like
python -m venv jsonl
jsonl/Scripts/pip install target-jsonl
```

Run the tap in discovery mode. Although none of the config vars are required, a `--config` arg is required, so pass `sample_config.json` from this directory:

```sh
bls/Scripts/tap-bls --config sample_config.json --discover > catalog.json
```

But that throws this error:

```
CRITICAL [Errno 2] No such file or directory: 'sample_config.json/state.json'
Traceback (most recent call last):
  File "path\to\bls\Scripts\tap-bls-script.py", line 11, in <module>
    load_entry_point('tap-bls==0.1.10', 'console_scripts', 'tap-bls')()
  File "path\to\bls\lib\site-packages\singer\utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "path\to\bls\lib\site-packages\tap_bls\__init__.py", line 42, in main
    generate_state()        # ... generate one
  File "path\to\bls\lib\site-packages\tap_bls\update_state.py", line 18, in generate_state
    with open(state_file, "w") as jsonFile:
FileNotFoundError: [Errno 2] No such file or directory: 'sample_config.json/state.json'
```

The issue seems to come from [this line](https://github.com/frasermarlow/tap-bls/blob/master/tap_bls/update_state.py#L15) returning `sample_config.json/state.json` and [this line](https://github.com/frasermarlow/tap-bls/blob/master/tap_bls/update_state.py#L18) trying to create a file with that path.

**Comment by frasermarlow** [comment]
Addressed in commit 78b62ed.  Better late than never.  Thanks.
